### ISSUE TITLE
`ValueError` when running from command line

### ISSUE THREAD

**Issue by sjfleming** [KenLauLab/dropkick#10]
Hello!  I'm new to dropkick, but interested in trying it out.  I've installed version 1.2.6

I am trying to run dropkick on a dataset from the command line.

I have downloaded the public 10x Genomics 8k PBMC dataset, as in
```
wget -O pbmc8k_raw_gene_bc_matrices.h5 https://cf.10xgenomics.com/samples/cell-exp/2.1.0/pbmc8k/pbmc8k_raw_gene_bc_matrices_h5.h5
```

Then I use `scanpy` to save the file in h5ad format, as follows:
```python
import scanpy as sc

adata = sc.read_10x_h5('pbmc8k_raw_gene_bc_matrices.h5')
adata.write('pbmc8k_raw_gene_bc_matrices.h5ad')
```

And then I try to run
```
dropkick run pbmc8k_raw_gene_bc_matrices.h5ad 
```
and I get the following

```er
Reading in unfiltered counts from pbmc8k_raw_gene_bc_matrices.h5ad/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
 - 737280 barcodes and 33694 genes
Ignoring 680489 barcodes with less than 50 genes detected
Ignoring 12061 genes with zero total counts
Top 10 ambient genes have dropout rates between 13.888 and 49.168 percent:
	['MALAT1', 'B2M', 'TMSB4X', 'EEF1A1', 'RPL21', 'RPS27', 'RPL13', 'RPL13A', 'RPL10', 'RPS18']
Determining 2000 highly variable genes
Setting arcsinh_norm layer to .X
Thresholding on heuristics for training labels:
	['arcsinh_n_genes_by_counts']
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
Ignoring 41697 barcodes below first threshold on arcsinh_n_genes_by_counts
Training dropkick with alphas:
	[0.1]
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
[Parallel(n_jobs=2)]: Done   5 out of   5 | elapsed:  2.5min finished
Chosen lambda value:
	[0.01699226]
Assigning scores and labels
Traceback (most recent call last):
  File "/home/sfleming/miniconda/envs/dropkick/bin/dropkick", line 8, in <module>
    sys.exit(main())
  File "/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/dropkick/__main__.py", line 293, in main
    args.func(args)
  File "/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/dropkick/__main__.py", line 63, in run
    verbose=args.verbose,
  File "/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/dropkick/api.py", line 639, in dropkick
    ] = rc_.coef_.squeeze()
  File "/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/pandas/core/indexing.py", line 723, in __setitem__
    iloc._setitem_with_indexer(indexer, value, self.name)
  File "/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/pandas/core/indexing.py", line 1677, in _setitem_with_indexer
    empty_value[indexer[0]] = arr
ValueError: shape mismatch: value array of shape (2000,) could not be broadcast to indexing result of shape (2003,)
```

I got the same sort of shape mismatch `ValueError` when running on another dataset as well.

Should I not use the command line version of the tool, but rather do things interactively in python?

**Comment by codyheiser** [comment]
I'm noticing the 
```
/home/sfleming/miniconda/envs/dropkick/lib/python3.7/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")
```
warning throughout your traceback.  I would try the following prior to re-running dropkick:
```
import scanpy as sc

adata = sc.read_10x_h5('pbmc8k_raw_gene_bc_matrices.h5')
adata.var_names_make_unique()
adata.write('pbmc8k_raw_gene_bc_matrices.h5ad')
```

My guess is that there are somehow 3 highly-variable gene features with duplicate names (hence the 2000 -> 2003 shape casting error), that are getting pulled into the analysis by their index and messing up downstream storage of model coefficients.

**Comment by sjfleming** [comment]
Excellent, thank you for the quick suggestion, I will try that now!

**Comment by sjfleming** [comment]
You were right!  Thank you very much!

```console
$ dropkick run pbmc8k_raw_gene_bc_matrices.h5ad 

Reading in unfiltered counts from pbmc8k_raw_gene_bc_matrices.h5ad - 737280 barcodes and 33694 genes
Ignoring 680489 barcodes with less than 50 genes detected
Ignoring 12061 genes with zero total counts
Top 10 ambient genes have dropout rates between 13.888 and 49.168 percent:
	['MALAT1', 'B2M', 'TMSB4X', 'EEF1A1', 'RPL21', 'RPS27', 'RPL13', 'RPL13A', 'RPL10', 'RPS18']
Determining 2000 highly variable genes
Setting arcsinh_norm layer to .X
Thresholding on heuristics for training labels:
	['arcsinh_n_genes_by_counts']
Ignoring 41697 barcodes below first threshold on arcsinh_n_genes_by_counts
Training dropkick with alphas:
	[0.1]
[Parallel(n_jobs=2)]: Using backend ThreadingBackend with 2 concurrent workers.
[Parallel(n_jobs=2)]: Done   5 out of   5 | elapsed:  2.7min finished
Chosen lambda value:
	[0.01699226]
Assigning scores and labels
Done!

Writing updated counts to ./pbmc8k_raw_gene_bc_matrices_dropkick.h5ad
Saving coefficient plot to ./pbmc8k_raw_gene_bc_matrices_coef.png
Saving score plot to ./pbmc8k_raw_gene_bc_matrices_score.png
```
