### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument

### ISSUE THREAD

**Issue by katze99** [KenLauLab/dropkick#8]
Thanks for this great tool!

I got the below error when I run dropkick
```
dropkick run ~/GSM4432647_EC3_raw_gene_bc_matrices_h5.h5ad

Reading in unfiltered counts from /root/GSM4432647_EC3_raw_gene_bc_matrices_h5.h5adTraceback (most recent call last):
  File "/usr/local/bin/dropkick", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/dropkick/__main__.py", line 293, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/dropkick/__main__.py", line 49, in run
    adata, name = prepare(args)
  File "/usr/local/lib/python3.8/dist-packages/dropkick/__main__.py", line 32, in prepare
    adata = sc.read(args.counts)
  File "/usr/local/lib/python3.8/dist-packages/scanpy/readwrite.py", line 112, in read
    return _read(
  File "/usr/local/lib/python3.8/dist-packages/scanpy/readwrite.py", line 713, in _read
    return read_h5ad(filename, backed=backed)
  File "/usr/local/lib/python3.8/dist-packages/anndata/_io/h5ad.py", line 254, in read_h5ad
    return AnnData(**d)
TypeError: __init__() got an unexpected keyword argument 'GRCh38-1.2.0_premrna'

**Comment by codyheiser** [comment]
Hello,

It looks like the error you're seeing comes directly during the reading of your `.h5ad` - specifically when invoking `scanpy.read()` pointed to your `GSM4432647_EC3_raw_gene_bc_matrices_h5.h5ad` file.  I would ensure that this file was generated properly using scanpy and saved to an `.h5ad` compressed file without any problems.

Perhaps this issue would be better served in the [scanpy](https://github.com/theislab/scanpy) or [anndata](https://github.com/theislab/anndata) repository?

I hope this helps.

**Comment by katze99** [comment]
Thank you for quick help!

I imported `GSM4432647_EC3_raw_gene_bc_matrices_h5.h5ad` to R by `Seurat` and made Seurat object. Then converted Seurat object to `.h5ad` file. Now `dropkick` is working perfectly with this reconverted file.
